src/meals/urls.py
from django.urls import path
from . import views


app_name = 'meals'


urlpatterns = [
    path('', views.meal_list , name= 'meal_list'),
    path('<slug:slug>', views.meal_detail , name= 'meal_detail')
]

src/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls', namespace='meals')),
    path('reserve_table/', include('reservation.urls', namespace='reservation'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reservation/urls.py
from django.urls import path
from . import views


app_name = 'reservation'


urlpatterns = [
    path('', views.reserve_table , name= 'reserve_table')
]

src/meals/models.py
from distutils.command.upload import upload
from operator import mod
from tabnanny import verbose
from xml.dom import NoModificationAllowedErr
from django.db import models
from django.utils.text import slugify

class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    preperation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null= True)

    def save(self, *args, **kvargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals, self).save(*args,**kvargs)

    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

src/reservation/models.py
from os import name
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def only_int(value): 
        if value.isdigit()==False:
            raise ValidationError('ID contains characters')

class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=20,validators=[only_int])
    number_of_person = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.name

    

src/reservation/forms.py
from dataclasses import field
from django import forms
from .models import Reservation

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class ReserveTableForm(forms.ModelForm):
    

    class Meta:
        model = Reservation
        fields = '__all__'
        widgets = {
            'date': DateInput(),
            'time': TimeInput()
        }

src/meals/views.py
from django.shortcuts import render
from .models import Meals ,Category

def meal_list(request):
    meal_list = Meals.objects.all()
    categories = Category.objects.all()
    context = {
        'meal_list' : meal_list,
        'categories': categories}
    return render(request, 'Meals/list.html', context)

def meal_detail(request ,slug):
    meal_detail= Meals.objects.get(slug=slug)
    context = {'meal_detail' : meal_detail}
    return render(request, 'Meals/detail.html', context)

src/reservation/views.py
from multiprocessing import context
import re
from django.shortcuts import render

from reservation.models import Reservation
from .models import Reservation
from .forms import ReserveTableForm



def reserve_table(request):
    reserve_form = ReserveTableForm()
    if request.method == 'POST':
        reserve_form = ReserveTableForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()
    context = {'form' : reserve_form}
    return render(request, 'Reservation/reservation.html' , context)

src/meals/templates/Meals/detail.html
{% extends 'base.html' %}
{% block body %}
   <section id="main-menu" class="menu-cart scroll-reveal">
       <div class="container">

        <img class="meal_img" src="{{meal_detail.image.url}} " alt="">
        <h2>{{meal_detail}}</h2>
        <p>{{meal_detail.description}}</p>
        <p>for: {{meal_detail.people}} People</p>
        <p>Preparation Time: {{meal_detail.preperation_time}} Minutes</p>
        <p>Price: {{meal_detail.price}} Ft</p>
       </div>
       <!--.container-->
   </section>
   <!--.menu-cart-->
   {% endblock body%}

   

src/meals/templates/Meals/list.html
 {% extends 'base.html' %}
 {% block body %}
    <section id="main-menu" class="menu-cart scroll-reveal">
        <div class="container">
            <h1 class="header-txt">Menu Cart</h1>
            <div class="divider">
                <?xml version="1.0" encoding="utf-8"?>
                <!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1930 255.5" style="enable-background:new 0 0 1930 255.5;" xml:space="preserve">
                                <style type="text/css">
                                    .st0{fill:none;stroke:#3c3c3c;stroke-width:10;stroke-linecap:square;stroke-miterlimit:10;}
                                </style>
                                <polyline class="st0" points="1224,171.8 1181.3,171.8 1139.2,129.6 1065,203.9 970.5,110.4 876,203.6 801.8,129.4 759.7,171.5 
                                    717,171.5 "/>
                                <polyline class="st0" points="5,131.5 757.3,131.5 801.8,176.1 885.9,91.9 868.3,74.2 831.5,111 870.4,149.9 970.2,50.2 1070,149.9 
                                    1108.8,111 1072.1,74.2 1054.4,91.9 1138.5,176.1 1183.1,131.5 1925,131.5 "/>
                                <rect x="921.9" y="26.7" transform="matrix(0.7071 -0.7071 0.7071 0.7071 231.426 707.2043)" class="st0" width="95" height="95"/>
                                <rect x="921.9" y="99.7" transform="matrix(0.7071 -0.7071 0.7071 0.7071 179.8072 728.5855)" class="st0" width="95" height="95"/>
                                <rect x="940.3" y="178.1" transform="matrix(0.7071 -0.7071 0.7071 0.7071 137.3893 746.1556)" class="st0" width="58.2" height="58.2"/>
                                </svg>
            </div>
            <!--.divider-->
            <ul class="menu-navigation" data-tabs data-match-height="true" id="example-tabs">
                {% for category in categories %}
                {% if forloop.counter == 1 %}
                <li class="tabs-title is-active"><a class="m-anim" data-tabs-target="{{ category|cut:" " }}" href="{{category|cut:" "}}" data-text="{{category}}">{{category}}</a></li>
                {% else %} 
                <li class="tabs-title"><a class="m-anim" data-tabs-target="{{category|cut:" "}}" href="{{category|cut:" "}}" data-text="{{category}}">{{category}}</a></li>
                {% endif %} 
                {% endfor %}
            </ul>

            <div class="tabs-content" data-tabs-content="example-tabs">
                {% for category in categories %}
                {% if forloop.counter == 1 %}
                <div class="tabs-panel is-active" id="{{category|cut:" "}}">
                    <div class="menu-content">
                        <div class="menu-section">
                            <table>
                            {% for meal in meal_list  %}
                            {% if forloop.counter|divisibleby:2 and meal.category == category%}
                            
                            <tr>
                                <td><a href={% url 'meals:meal_detail' meal.slug%}><span>{{meal.name}} </span></td>
                                <td><span>{{meal.price}}</span></td>
                            </tr>
                            <tr>
                                <td>{{meal.description}}</td>
                            </tr>
                                 
                            {% endif %}   
                            {% endfor %}
                            </table>
                        </div>
                        <!--.menu-section-->
                        <div class="menu-section">
                            <table>
                                {% for meal in meal_list  %}
                                {% if not forloop.counter|divisibleby:2 and meal.category == category%}
                                <tr>
                                    <td><a href={% url 'meals:meal_detail' meal.slug%}><span>{{meal.name}} </span></td>
                                    <td><span>{{meal.price}}</span></td>
                                </tr>
                                <tr>
                                    <td>{{meal.description}}</td>
                                </tr>
                                     
                                {% endif %}   
                                {% endfor %}
                                </table>
                        </div> 
                        <!--.menu-section-->
                    </div>
                    <!--.menu-content-->
                </div>
                {% else %} 
                <div class="tabs-panel" id="{{category|cut:" "}}">
                    <div class="menu-content">
                        <div class="menu-section">
                            <table>
                            {% for meal in meal_list  %}
                            {% if forloop.counter|divisibleby:2 and meal.category == category%}
                            
                            <tr>
                                <td><a href={% url 'meals:meal_detail' meal.slug%}><span>{{meal.name}} </span></td>
                                <td><span>{{meal.price}}</span></td>
                            </tr>
                            <tr>
                                <td>{{meal.description}}</td>
                            </tr>
                                 
                            {% endif %}   
                            {% endfor %}
                            </table>
                        </div>
                        <!--.menu-section-->
                        <div class="menu-section">
                            <table>
                                {% for meal in meal_list  %}
                                {% if not forloop.counter|divisibleby:2 and meal.category == category%}
                                <tr>
                                    <td><a href={% url 'meals:meal_detail' meal.slug%}><span>{{meal.name}} </span></td>
                                    <td><span>{{meal.price}}</span></td>
                                </tr>
                                <tr>
                                    <td>{{meal.description}}</td>
                                </tr>
                                     
                                {% endif %}   
                                {% endfor %}
                                </table>
                        </div> 
                        <!--.menu-section-->
                    </div>
                    <!--.menu-content-->
                </div>
                {% endif %}
                
                
                
                <!--#panel1-->
                {% endfor %}    

            </div>
        </div>
        <!--.container-->
    </section>
    <!--.menu-cart-->
    {% endblock body%}

    

src/meals/templates/Meals/list_old.html
{% extends 'base.html' %}
{% block body  %}
	<!-- Start Menu -->
	<div class="menu-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>Special Menu</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
					</div>
				</div>
			</div>
			
			<div class="row inner-menu-box">
				<div class="col-3">
					<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
						<a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">All</a>
						<a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Drinks</a>
						<a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Lunch</</a>
						<a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Dinner</a>
					</div>
				</div>
				
				<div class="col-9">
					<div class="tab-content" id="v-pills-tabContent">
						<div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
							<div class="row">

								{% for  meal in meal_list%}
								<div class="col-lg-4 col-md-6 special-grid drinks">
									<div class="gallery-single fix">
										<img src="images/img-01.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>{{meal.name}}</h4>
											<p>{{meal.describtion}}</p>
											<h5>{{meal.price}}</h5>
										</div>
									</div>
								</div>
								{% endfor %}	

							</div>
							
						</div>
						<div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
							<div class="row">
								<div class="col-lg-4 col-md-6 special-grid drinks">
									<div class="gallery-single fix">
										<img src="images/img-01.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Drinks 1</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $7.79</h5>
										</div>
									</div>
								</div>
								
								<div class="col-lg-4 col-md-6 special-grid drinks">
									<div class="gallery-single fix">
										<img src="images/img-02.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Drinks 2</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $9.79</h5>
										</div>
									</div>
								</div>
								
								<div class="col-lg-4 col-md-6 special-grid drinks">
									<div class="gallery-single fix">
										<img src="images/img-03.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Drinks 3</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $10.79</h5>
										</div>
									</div>
								</div>
							</div>
							
						</div>
						<div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
							<div class="row">
								<div class="col-lg-4 col-md-6 special-grid lunch">
									<div class="gallery-single fix">
										<img src="images/img-04.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Lunch 1</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $15.79</h5>
										</div>
									</div>
								</div>
								
								<div class="col-lg-4 col-md-6 special-grid lunch">
									<div class="gallery-single fix">
										<img src="images/img-05.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Lunch 2</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $18.79</h5>
										</div>
									</div>
								</div>
								
								<div class="col-lg-4 col-md-6 special-grid lunch">
									<div class="gallery-single fix">
										<img src="images/img-06.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Lunch 3</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $20.79</h5>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
							<div class="row">
								<div class="col-lg-4 col-md-6 special-grid dinner">
									<div class="gallery-single fix">
										<img src="images/img-07.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Dinner 1</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $25.79</h5>
										</div>
									</div>
								</div>
								
								<div class="col-lg-4 col-md-6 special-grid dinner">
									<div class="gallery-single fix">
										<img src="images/img-08.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Dinner 2</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $22.79</h5>
										</div>
									</div>
								</div>
								
								<div class="col-lg-4 col-md-6 special-grid dinner">
									<div class="gallery-single fix">
										<img src="images/img-09.jpg" class="img-fluid" alt="Image">
										<div class="why-text">
											<h4>Special Dinner 3</h4>
											<p>Sed id magna vitae eros sagittis euismod.</p>
											<h5> $24.79</h5>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
	{% endblock body  %}

src/meals/templates/Meals/list_removed.html
<h1>Meals List</h1>

{% for  meal  in meal_list  %}
<h2> <a href="{% url 'meals:meal_detail' meal.slug %}"> {{meal}} </a> </h2>
{% endfor %}

src/reservation/templates/Reservation/reservation.html
{% extends 'base.html' %}
{% block body  %}
<section id="main-menu" class="menu-cart scroll-reveal">
    <div class="container">
        <h1 class="header-txt">Reservation</h1>
        <div class="divider">
            <?xml version="1.0" encoding="utf-8"?>
            <!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1930 255.5" style="enable-background:new 0 0 1930 255.5;" xml:space="preserve">
                            <style type="text/css">
                                .st0{fill:none;stroke:#3c3c3c;stroke-width:10;stroke-linecap:square;stroke-miterlimit:10;}
                            </style>
                            <polyline class="st0" points="1224,171.8 1181.3,171.8 1139.2,129.6 1065,203.9 970.5,110.4 876,203.6 801.8,129.4 759.7,171.5 
                                717,171.5 "/>
                            <polyline class="st0" points="5,131.5 757.3,131.5 801.8,176.1 885.9,91.9 868.3,74.2 831.5,111 870.4,149.9 970.2,50.2 1070,149.9 
                                1108.8,111 1072.1,74.2 1054.4,91.9 1138.5,176.1 1183.1,131.5 1925,131.5 "/>
                            <rect x="921.9" y="26.7" transform="matrix(0.7071 -0.7071 0.7071 0.7071 231.426 707.2043)" class="st0" width="95" height="95"/>
                            <rect x="921.9" y="99.7" transform="matrix(0.7071 -0.7071 0.7071 0.7071 179.8072 728.5855)" class="st0" width="95" height="95"/>
                            <rect x="940.3" y="178.1" transform="matrix(0.7071 -0.7071 0.7071 0.7071 137.3893 746.1556)" class="st0" width="58.2" height="58.2"/>
                            </svg>
        </div>
        <!--.divider-->
        <div class="contact-form scroll-reveal" data-origin="bottom" data-distance="30%">
            
         {% comment %} <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Name" for="{{ form.name }}" >
                <input type="email" name="email" placeholder="Email" for="{{ form.email }}" >
                <input type="phone2numeric" name="phone" placeholder="Phone" for="{{ form.phone }}">
                <input for="{{ form.number_of_person }}">
                <input type="date" name="date" placeholder="Date" for="{{ form.date }}">
                <input type="time" name="time" placeholder="Time" value="20:00" for="{{ form.time }}">
                <button type ="submit" class="send-form">Send</button>
            </form>  {% endcomment %}
             <form action="" method="post">
                 {% csrf_token %}
                 {{form.as_p}}

                 <button type ="submit" class="send-form">Send</button>     
            </form>
        </div>
    </div>
    <!--.container-->
</section>
    {% comment %} <footer id="contact-us">
        <div class="container">
            <div class="footer-content">
                <h1 class="header-txt scroll-reveal">Contact</h1>
                <div class="divider scroll-reveal">
                    <?xml version="1.0" encoding="utf-8"?>
                    <!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1930 255.5" style="enable-background:new 0 0 1930 255.5;" xml:space="preserve">
                                <style type="text/css">
                                    .st0{fill:none;stroke:#3c3c3c;stroke-width:10;stroke-linecap:square;stroke-miterlimit:10;}
                                </style>
                                <polyline class="st0" points="1224,171.8 1181.3,171.8 1139.2,129.6 1065,203.9 970.5,110.4 876,203.6 801.8,129.4 759.7,171.5 
                                    717,171.5 "/>
                                <polyline class="st0" points="5,131.5 757.3,131.5 801.8,176.1 885.9,91.9 868.3,74.2 831.5,111 870.4,149.9 970.2,50.2 1070,149.9 
                                    1108.8,111 1072.1,74.2 1054.4,91.9 1138.5,176.1 1183.1,131.5 1925,131.5 "/>
                                <rect x="921.9" y="26.7" transform="matrix(0.7071 -0.7071 0.7071 0.7071 231.426 707.2043)" class="st0" width="95" height="95"/>
                                <rect x="921.9" y="99.7" transform="matrix(0.7071 -0.7071 0.7071 0.7071 179.8072 728.5855)" class="st0" width="95" height="95"/>
                                <rect x="940.3" y="178.1" transform="matrix(0.7071 -0.7071 0.7071 0.7071 137.3893 746.1556)" class="st0" width="58.2" height="58.2"/>
                                </svg>
                </div>
                <!--.divider-->
                <div class="contact-info scroll-reveal">
                    <div class="info-address">
                        <h3>Veggie</h3>
                        <p>3428 Magnolia Avenue<br>Hackettstown, NJ 07840</p>
                    </div>
                    <div class="reservations">
                        <h3>Reservations</h3>
                        <p>reservations@vegggie.com<br>+48 202-555-0114</p>
                    </div>
                </div>
                <!--.contact-info-->
                <div class="contact-form scroll-reveal" data-origin="bottom" data-distance="30%">
                    <h3>Contact us</h3>
                  <form action="" method="post">
                        {% csrf_token %}
                        <input type="text" name="name" placeholder="Name" for="{{ form.name }}" >
                        <input type="email" name="email" placeholder="Email" for="{{ form.email }}" >
                        <input type="phone2numeric" name="phone" placeholder="Phone" for="{{ form.phone }}">
                        <input for="{{ form.number_of_person }}">
                        <input type="date" name="date" placeholder="Date" for="{{ form.date }}">
                        <input type="time" name="time" placeholder="Time" value="20:00" for="{{ form.time }}">
                        <button type ="submit" class="send-form">Send</button>
                    </form>  
                     <form action="" method="post">
                         {% csrf_token %}
                         {{form}}

                         <button type ="submit" class="send-form">Send</button>     
                    </form>
                </div>
                <!--.contact-form-->
                <div class="social-icons scroll-reveal" data-duration="1500">
                    <div class="fb-i">

                        <?xml version="1.0" encoding="iso-8859-1"?>
                        <!-- Generator: Adobe Illustrator 19.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 288.861 288.861" style="enable-background:new 0 0 288.861 288.861;" xml:space="preserve" width="30px" height="30px">
                                <path d="M167.172,288.861h-62.16V159.347H70.769v-59.48h34.242v-33.4C105.011,35.804,124.195,0,178.284,0   c19.068,0,33.066,1.787,33.651,1.864l5.739,0.746l-1.382,55.663l-6.324-0.058c-0.013,0-14.223-0.135-29.724-0.135   c-11.536,0-13.066,2.847-13.066,14.171v27.629h50.913l-2.821,59.48h-48.086v129.501H167.172z M117.858,276.007h36.453V146.5h48.677   l1.607-33.779h-50.284V72.238c0-13.368,3.078-27.025,25.919-27.025c9.178,0,17.899,0.045,23.509,0.09l0.778-31.292   c-5.675-0.508-15.116-1.157-26.247-1.157c-44.544,0-60.419,27.693-60.419,53.613v46.254H83.61V146.5h34.242v129.507H117.858z" fill="#3c3c3c"/>
                            </svg>
                    </div>
                    <div class="insta-i">
                        <?xml version="1.0" encoding="iso-8859-1"?>
                        <!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 48 48" style="enable-background:new 0 0 48 48;" xml:space="preserve" width="30px" height="30px">
                            <path d="M40.4,5.5H35.6c-1.434,0-2.6,1.166-2.6,2.6V12.9c0,1.434,1.166,2.6,2.6,2.6H40.4c1.434,0,2.6-1.166,2.6-2.6V8.1    C43,6.666,41.834,5.5,40.4,5.5z M41,12.9c0,0.331-0.269,0.6-0.6,0.6H35.6c-0.331,0-0.6-0.269-0.6-0.6V8.1    c0-0.331,0.269-0.6,0.6-0.6H40.4c0.331,0,0.6,0.269,0.6,0.6V12.9z" fill="#3c3c3c"/>
                            <path d="M37.8,0.5H10.2C4.576,0.5,0,5.089,0,10.731V17.5v2v17.77C0,42.911,4.576,47.5,10.2,47.5h27.6    c5.624,0,10.2-4.589,10.2-10.23V19.5v-2v-6.769C48,5.089,43.424,0.5,37.8,0.5z M46,37.27c0,4.538-3.679,8.23-8.2,8.23H10.2    c-4.522,0-8.2-3.692-8.2-8.23V19.5h12.221C11.62,22.043,10,25.584,10,29.5c0,7.72,6.28,14,14,14s14-6.28,14-14    c0-3.916-1.62-7.457-4.221-10H46V37.27z M36,29.5c0,6.617-5.383,12-12,12s-12-5.383-12-12s5.383-12,12-12S36,22.883,36,29.5z     M31.174,17.5c-2.101-1.261-4.55-2-7.174-2s-5.073,0.739-7.174,2H2v-6.769C2,6.192,5.679,2.5,10.2,2.5h27.6    c4.521,0,8.2,3.692,8.2,8.231V17.5H31.174z" fill="#3c3c3c"/>
                            <path d="M15,29.5c0,4.962,4.037,9,9,9s9-4.038,9-9s-4.037-9-9-9S15,24.538,15,29.5z M31,29.5c0,3.86-3.141,7-7,7s-7-3.14-7-7    s3.141-7,7-7S31,25.64,31,29.5z" fill="#3c3c3c"/>

                        </svg>
                    </div>
                </div>
                <!--.social-icons-->
            </div>
            <!--.footer-content-->
            <p class="copy-info">Copyright 2017 © by Anna Dadej</p>
        </div>
        <!--.container-->
    </footer> {% endcomment %}

    {% endblock body  %}%}